wandb_version: 1

epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.005
csv_path:
  desc: null
  value: ../../preprocessed.csv
architecture:
  desc: null
  value: LSTM Autoencoder
subset_size:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715759652
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.12.3
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
